### ISSUE TITLE
Fatal error after restarting a workflow

### ISSUE THREAD

**Issue by nsouedet** [populse/soma-workflow#67]
I was using BrainVISA on the master branch in a casa-dev 5.0-8 environment and I restarted a workflow, that lead to the following fatal python error :
```python
Traceback (most recent call last):
  File "/casa/host/build/python/soma_workflow/gui/workflowGui.py", line 3427, in refresh
    self.updatePlot()
  File "/casa/host/build/python/soma_workflow/gui/workflowGui.py", line 3438, in updatePlot
    self.jobsFctTime()
  File "/casa/host/build/python/soma_workflow/gui/workflowGui.py", line 3567, in jobsFctTime
    self.figure.autofmt_xdate(rotation=80)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 609, in autofmt_xdate
    for label in self.axes[0].get_xticklabels(which=which):
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 1248, in get_ticklabels
    return self.get_majorticklabels()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 1207, in get_majorticklabels
    ticks = self.get_major_ticks()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 1378, in get_major_ticks
    numticks = len(self.get_majorticklocs())
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 1283, in get_majorticklocs
    return self.major.locator()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/dates.py", line 1327, in __call__
    return locator()
  File "/usr/lib/python3/dist-packages/pandas/plotting/_converter.py", line 473, in __call__
    freq=freq, tz=tz).astype(object)
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/datetimes.py", line 2749, in date_range
    closed=closed, **kwargs)
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/datetimes.py", line 381, in __new__
    ambiguous=ambiguous)
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/datetimes.py", line 476, in _generate
    start = Timestamp(start)
  File "pandas/_libs/tslibs/timestamps.pyx", line 644, in pandas._libs.tslibs.timestamps.Timestamp.__new__
  File "pandas/_libs/tslibs/conversion.pyx", line 300, in pandas._libs.tslibs.conversion.convert_to_tsobject
  File "pandas/_libs/tslibs/conversion.pyx", line 380, in pandas._libs.tslibs.conversion.convert_datetime_to_tsobject
  File "pandas/_libs/tslibs/np_datetime.pyx", line 121, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 53-03-14 10:46:24
Fatal Python error: Aborted

Thread 0x00007fdcf903e700 (most recent call first):
  File "/casa/host/build/python/soma_workflow/database_server.py", line 1721 in pop_workflow_ended_transfer
  File "/casa/host/build/python/soma_workflow/engine.py", line 427 in start_loop
  File "/casa/host/build/python/soma_workflow/engine.py", line 102 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fdcf883d700 (most recent call first):
  File "/casa/host/build/python/soma_workflow/schedulers/local_scheduler.py", line 139 in loop
  File "/usr/lib/python3.6/threading.py", line 864 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007fde26afa740 (most recent call first):
  File "/casa/host/build/brainvisa/neuro.py", line 304 in <module>
  File "<string>", line 9 in execfile
  File "<string>", line 32 in <module>
Aborted (core dumped)
```

I am not sure this is always reproducible.

**Comment by denisri** [comment]
I can't reproduce the issue, but I have fixed another problem (when a date is None). Is this ticket still valid ?
