### ISSUE TITLE
Error when trying to use dynamic process in som-workflow

### ISSUE THREAD

**Issue by Hboni** [populse/soma-workflow#70]
I am using brainvisa in casa-distro with the image "casa-dev-5.0-4".

I wanted to run in parallel a pipeline that contains a process that has a dynamic signature. This process is the `SPM12 - Deformations : composition - generic` process (SPM > spm12 > utils > spm12 - Deformation composition - generic). This process allows combining multiple deformation files to create a new one.

When I try to run in parallel my main pipeline containing this process, I get this error: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/casa/host/build/python/brainvisa/axon/runprocess.py", line 474, in <module>
    process = get_process_with_params(process_name, iterated, *args, **kwargs)
  File "/casa/host/build/python/brainvisa/axon/runprocess.py", line 143, in get_process_with_params
    context._setArguments(*(process,) + tuple(args), **kwargs)
  File "/casa/host/build/python/brainvisa/processes.py", line 3027, in _setArguments
    n = list(_process.signature.keys())[i]
IndexError: list index out of range
```

I made a test with 2 deformations files and printed some info from "/casa/host/build/python/brainvisa/processes.py", line 3027, and I get this: 
```
print(list(_process.signature.keys()))
>>> ['deformation_number', 'deformation_type_1', 'custom_outputs', 'output_destination', 'output_directory', 'save_as', 'output_deformation', 'batch_location']
```
We can see that the signature used here corresponds to the signature of the process at the initialization, without the update of the number of deformations. What is expected when the process is filled is:
```
>>> ['deformation_number', 'deformation_type_1', 'deformation_type_2', 'custom_outputs', 'output_destination', 'output_directory', 'save_as', 'output_deformation', 'batch_location', 'deformation_field_1', 'deformation_field_2']
```
Which correspond to the parameters of the call of the process:
```
'python' '-m' 'brainvisa.axon.runprocess' 'SPM12composition_generic' 2 'deformation' 'deformation' True 'output' None None '/tmp/deformation_result.nii' '/tmp/spm12_deformation_composition_job.m' '/tmp/deformation_1.nii.gz' '/tmp/deformation_2.nii.gz'
```

So it seems to not take into account the modification of the signature. Is it possible to use the updated signature and not only the initial signature?

**Comment by Hboni** [comment]
To reproduce the bug, we can create a simple pipeline like this one, and put 2 deformation files as input : 
```
from brainvisa.processes import Signature, ReadDiskItem, WriteDiskItem
from brainvisa.processes import getAllFormats
from brainvisa.processes import ProcessExecutionNode
from brainvisa.processes import ParallelExecutionNode

name = 'Test'
userLevel = 0

signature = Signature(
    'deformation_1', ReadDiskItem('4D Volume', getAllFormats()),
    'deformation_2', ReadDiskItem('4D Volume', getAllFormats()),
    
    'output_deformation', WriteDiskItem('4D Volume', getAllFormats())
)


def initialization(self):
    self.main_node = ParallelExecutionNode(self.name, parameterized=self)
    self.main_node.addChild('composition',
                            ProcessExecutionNode('SPM12composition_generic',
                                                 optional=True,
                                                 altname='composition_test'))
    self.main_node.composition.deformation_number = 2
    self.main_node.composition.deformation_type_1 = 'deformation'
    self.main_node.composition.deformation_type_2 = 'deformation'
    self.main_node.composition.custom_outputs = True

    self.main_node.addLink('composition.deformation_field_1', 'deformation_1')
    self.main_node.addLink('composition.deformation_field_2', 'deformation_2')
    self.main_node.addLink('composition.output_deformation', 'output_deformation')

    self.setExecutionNode(self.main_node)

```

**Comment by denisri** [comment]
Processes with a dynamic signature change their signature when some of their parameters change, using callbacks. Thus it depends on the order parameters are set - but here it seems OK because the first parameter, `deformation_number` it the one which should trigger the signature change. So I guess the callback is not executed at the right time, or not enabled during process init from a commandline. I will try to look.

**Comment by denisri** [comment]
By the way, this problem is in Axon, not in soma-workflow: I'm moving the ticket.

**Comment by denisri** [comment]
Well it seems not possible to transfer a ticket to a different organization (populse -> brainvisa) in github. I open a new one there:
brainvisa/axon#61.
